### ISSUE TITLE
update patch instructions

### ISSUE THREAD

**Issue by orbeckst** [amruthesht/namd-3.0-IMDv3-patch#2]
## source code version

State which exact version of the NAMD3 source code you used:
- version number
- anything else (eg from version control commit ID from _their_ repo)

You want to be crystal-clear about which version of the source code is known to work with your patch.

## patch command
Does one get the NAMD source code as a git repo? If yes, then `git apply` will work, but if you get it as a tarball, you should provide an invocation of [`patch`](https://www.man7.org/linux/man-pages/man1/patch.1.html).

**Comment by orbeckst** [comment]
ping @amruthesht

**Comment by amruthesht** [comment]
The exact version number is already on the current README file.
To make it more clear, I have added the link of the particular release (NAMD 3.0) and its source code to the README.
